### DISCUSSION TITLE
CI/CD Workflow

### DISCUSSION THREAD

**Discussion by gbowne1** [gbowne1/gradebook-management-system#23] [Ideas]
I thought some about a GitHub action or workflow for CI/CD for this project.

Thoughts @andrewlod?

```yaml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Replace with desired runner OS
    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Install dependencies (adapt for your package manager)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
          # Install gtest (adapt for your package manager)

      - name: Configure CMake
        working-directory: ${{ github.workspace }}  # Root of the project
        run: cmake -B build

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: make

      - name: Run tests (if testing enabled)
        working-directory: ${{ github.workspace }}/build
        run: |
          if [[ "${{ env.BUILD_LIBRARY }}" == "ON" ]]; then
            ctest -V
          else
            echo "Testing skipped for non-library builds."
          fi
        env:
          BUILD_LIBRARY: ${{ job.needs.configure.outputs.BUILD_LIBRARY }}  # Inherit from configure step

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v3  # Upload test results for later analysis
        if: always()  # Upload even on failures for troubleshooting
        with:
          name: test-results
          path: ${{ github.workspace }}/build/Testing/*
```
